/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:47bf3150-650f-472d-a2da-3028efa49f66",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_2cBx7Y2na",
    "aws_user_pools_web_client_id": "3qmj1tkrevc85pemaj1oiofboa",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://5aii3epo4ffxxiginxn6lsy5fu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
